project:
  type: website
  output-dir: ../docs
  render:
    - "*.qmd"

website:
  title: "Gilmore rethinks"
  # announcement: 
  #   content: "The Week 11 Siegler & Alibali chapter is on Canvas now." 
  #   position: below-navbar
  #   icon: info-circle
  #   dismissable: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - ch-01-03.qmd
  repo-url: https://github.com/rogilmore/statistical-rethinking
  repo-actions: [edit, issue]
  repo-subdir: src
  page-footer:
    left: "Copyright © Rick Gilmore • [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)"
    center: "Built with [Quarto](https://quarto.org/)"
    right: 
      - icon: github
        href: https://github.com/rogilmore/statistical-rethinking
    background: light
    border: true
  page-navigation: true
  bread-crumbs: true
  reader-mode: false

format:
  html:
    theme: [cosmo, include/css/psu.scss]
    toc: true
    toc-depth: 4
    fig-align: center
    fontsize: 1.1em
    number-sections: false
    citations-hover: true
    footnotes-hover: true
    date-modified: last-modified
    date: today
    bibliography: include/bib/refs.bib
    csl: include/bib/apa.csl
    html-math-method: mathjax
    code-fold: true
    code-tools: true

  # pdf:
  #   documentclass: scrreprt
    